apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ph-transparente-route
spec:
  to:
    kind: Service
    name: ph-transparente-frontend
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
