apiVersion: v1
kind: Secret
metadata:
  name: ph-transparente-secrets
type: Opaque
stringData:
  # Cambiar estos valores antes de aplicar en Red Hat Sandbox
  database-url: "jdbc:postgresql://ph-postgresql:5432/phdb"
  database-username: "postgres"
  database-password: "postgres123"
  jwt-secret: "cGh0cmFuc3BhcmVudGVfc2VjcmV0X2tleV9kZXZfMjA0OA=="
  email-username: "phtransparente@gmail.com"
  email-password: "tu_contraseña_de_aplicacion"
